[[teams.wcgw]]
name = "Alex"
location = "America/Montreal"

[[teams.wcgw]]
name = "Jane Doe"
location = "Europe/Dublin"

[[teams.wcgw]]
name = "John Doe"
location = "Europe/Dublin"

[[teams.managers]]
name = "John Doe"
location = "Europe/Dublin"
