name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build and verify project
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Formatting
      run: cargo fmt --all -- --check
    - name: Build
      if: ${{ always() }}
      run: cargo build --verbose
    - name: Clippy
      if: ${{ always() }}
      run: cargo clippy -- -D warnings
    - name: Tests
      run: cargo test --verbose
